apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversaotemperatura
spec:
  replicas: 5
  selector:
    matchLabels:
      app: conversaotemperatura
  template:
    metadata:
      labels:
        app: conversaotemperatura
    spec:
      containers:
      - name: conversao-temperatura
        image: ygortfive/conversao-temperatura:v3
---
apiVersion: v1
kind: Service
metadata:
  name: conversao-temperatura
spec:
  selector:
    app: conversaotemperatura
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 30001
  type: NodePort
